version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"

    default_reviewers:
      - "CodexLink"

    default_assignees:
      - "CodexLink"

    default_labels:
      - "Library Dependency Update"
      - "Dependabot"